# Generated by Django 5.1.4 on 2025-02-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(default='', max_length=20, verbose_name='Genêro'),
        ),
    ]
