# Generated by Django 5.1.4 on 2024-12-10 19:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default='', max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(default='', max_length=100, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo'),
        ),
        migrations.CreateModel(
            name='ChavePIX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMAIL', 'E-mail'), ('CPF', 'CPF'), ('CELULAR', 'Número de celular')], default='CPF', max_length=20, verbose_name='Tipo de chave PIX')),
                ('valor', models.CharField(max_length=30, verbose_name='Valor da chave PIX')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
