# Generated by Django 5.1.4 on 2024-12-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0006_transacoes_chave_pix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacoes',
            options={},
        ),
        migrations.RemoveField(
            model_name='chavepix',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='chavepix',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='chavepix',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='transacoes',
            name='chave_pix',
        ),
        migrations.RemoveField(
            model_name='transacoes',
            name='data',
        ),
        migrations.RemoveField(
            model_name='transacoes',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='transacoes',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='transacoes',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha_pix',
        ),
    ]
