# Generated by Django 5.1.4 on 2024-12-30 20:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0007_alter_transacoes_options_remove_chavepix_tipo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChavePIX',
        ),
        migrations.DeleteModel(
            name='Transacoes',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default='', max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(default='', max_length=100, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='banco.genero'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha_pix',
            field=models.CharField(default='', max_length=19, verbose_name='Senha do pix'),
        ),
    ]
