# Generated by Django 5.1.4 on 2025-02-11 14:48

import banco.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0009_chavepix_transacoes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', banco.models.UsuarioManager()),
            ],
        ),
    ]
